# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
copy proxy-service-0.0.1-SNAPSHOT.jar /opt/lib/

copy proxy-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/proxy-service-entrypoint.sh

# Make port 8585 available to the world outside this container
EXPOSE 8585

# Add a volume pointing to /var/lib/proxy-repo
VOLUME /var/lib/proxy-repo