version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: .
            dockerfile: Dockerfile-config-server
        image: config-server:latest
        expose:
            - 8088
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    discovery-service:
        container_name: discovery-service
        build:
            context: .
            dockerfile: Dockerfile-discovery-service
        image: discovery-service:latest
        entrypoint: /opt/lib/config-discovery-client-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8061
        ports:
            - 8061:8061
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
        depends_on:
            - config-server
        logging:
            driver: json-file
    employee-service:
        container_name: employee-service
        build:
            context: .
            dockerfile: Dockerfile-employee-service
        image: employee-service:latest
        entrypoint: /opt/lib/employee-service-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8090
        ports:
            - 8090:8090
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
        depends_on:
            - config-server
            - discovery-service
        logging:
            driver: json-file  
    department-service:
        container_name: department-service
        build:
            context: .
            dockerfile: Dockerfile-department-service
        image: department-service:latest
        entrypoint: /opt/lib/department-service-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8091
        ports:
            - 8091:8091
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
            - employee-service:employee-service
        depends_on:
            - config-server
            - discovery-service
            - employee-service
        logging:
            driver: json-file
    organization-service:
        container_name: organization-service
        build:
            context: .
            dockerfile: Dockerfile-organization-service
        image: organization-service:latest
        entrypoint: /opt/lib/organization-service-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8092
        ports:
            - 8092:8092
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
            - employee-service:employee-service
            - department-service:department-service
        depends_on:
            - config-server
            - discovery-service
            - employee-service
            - department-service
        logging:
            driver: json-file
    gateway-service:
        container_name: gateway-service
        build:
            context: .
            dockerfile: Dockerfile-gateway-service
        image: gateway-service:latest
        entrypoint: /opt/lib/gateway-service-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8060
        ports:
            - 8060:8060
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
            - employee-service:employee-service
            - department-service:department-service
            - organization-service:organization-service
        depends_on:
            - config-server
            - discovery-service
            - employee-service
            - department-service
            - organization-service
        logging:
            driver: json-file
    proxy-service:
        container_name: proxy-service
        build:
            context: .
            dockerfile: Dockerfile-proxy-service
        image: proxy-service:latest
        entrypoint: /opt/lib/proxy-service-entrypoint.sh
        environment:
            SPRING_APPLICATION_JSON: '{"spring": {"cloud": {"config": {"uri": "http://config-server:8088"}}}}'
        expose:
            - 8585
        ports:
            - 8585:8585
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
            - discovery-service:discovery-service
            - employee-service:employee-service
            - department-service:department-service
            - organization-service:organization-service
            - gateway-service:gateway-service
        depends_on:
            - config-server
            - discovery-service
            - employee-service
            - department-service
            - organization-service
            - gateway-service
        logging:
            driver: json-file     
networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true