# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
copy organization-service-0.0.1-SNAPSHOT.jar /opt/lib/

copy organization-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/organization-service-entrypoint.sh

# Make port 8092 available to the world outside this container
EXPOSE 8092

# Add a volume pointing to /var/lib/organization-repo
VOLUME /var/lib/organization-repo


