# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
copy department-service-0.0.1-SNAPSHOT.jar /opt/lib/

COPY department-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/department-service-entrypoint.sh

# Make port 8091 available to the world outside this container
EXPOSE 8091

# Add a volume pointing to /var/lib/department-repo
VOLUME /var/lib/department-repo
