# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
COPY discovery-service-0.0.1-SNAPSHOT.jar /opt/lib/

COPY config-discovery-client-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/config-discovery-client-entrypoint.sh

# Make port 8061 available to the world outside this container
EXPOSE 8061

# Add a volume pointing to /var/lib/discovery-repo
VOLUME /var/lib/discovery-repo