# Start with a base image containing Java runtime
FROM alpine-jdk:base

MAINTAINER nagendra.kldm@gmail.com

RUN apk --no-cache add netcat-openbsd

# The application's jar file
copy gateway-service-0.0.1-SNAPSHOT.jar /opt/lib/

copy gateway-service-entrypoint.sh /opt/lib/

RUN chmod 755 /opt/lib/gateway-service-entrypoint.sh

# Make port 8060 available to the world outside this container
EXPOSE 8060

# Add a volume pointing to /var/lib/gateway-repo
VOLUME /var/lib/gateway-repo